[package]
name = "burnt_chroma"
version = "0.1.0"
edition = "2021"
description = "A general purpose image manipulation library"
readme = "README.md"
homepage = "https://jaspervaldivia.dev"
repository = "https://github.com/jasval/burnt_chroma"
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["anamorphic", "image", "desqueeze", "stretch"]
categories = ["multimedia::images", "multimedia", "graphics", "command-line-utilities", "external-ffi-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
debug = true

[profile.release]
debug = false

[dependencies]
image = "0.24.6"
tokio = "1.29.1"

[dev-dependencies]
arbitrary = "1.3.0"
test-case = "3.1.0"
mockall = "0.11.4"

[features]
debug_assertions = []
