// File automatically generated by swift-bridge.
typedef struct ImageFormat ImageFormat;
void __swift_bridge__$ImageFormat$_free(void* self);

void* __swift_bridge__$Vec_ImageFormat$new(void);
void __swift_bridge__$Vec_ImageFormat$drop(void* vec_ptr);
void __swift_bridge__$Vec_ImageFormat$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_ImageFormat$pop(void* vec_ptr);
void* __swift_bridge__$Vec_ImageFormat$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_ImageFormat$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ImageFormat$len(void* vec_ptr);
void* __swift_bridge__$Vec_ImageFormat$as_ptr(void* vec_ptr);

typedef struct ImageError ImageError;
void __swift_bridge__$ImageError$_free(void* self);

void* __swift_bridge__$Vec_ImageError$new(void);
void __swift_bridge__$Vec_ImageError$drop(void* vec_ptr);
void __swift_bridge__$Vec_ImageError$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_ImageError$pop(void* vec_ptr);
void* __swift_bridge__$Vec_ImageError$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_ImageError$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ImageError$len(void* vec_ptr);
void* __swift_bridge__$Vec_ImageError$as_ptr(void* vec_ptr);

typedef struct SqueezeFactor SqueezeFactor;
void __swift_bridge__$SqueezeFactor$_free(void* self);

void* __swift_bridge__$Vec_SqueezeFactor$new(void);
void __swift_bridge__$Vec_SqueezeFactor$drop(void* vec_ptr);
void __swift_bridge__$Vec_SqueezeFactor$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_SqueezeFactor$pop(void* vec_ptr);
void* __swift_bridge__$Vec_SqueezeFactor$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_SqueezeFactor$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_SqueezeFactor$len(void* vec_ptr);
void* __swift_bridge__$Vec_SqueezeFactor$as_ptr(void* vec_ptr);

void __swift_bridge__$desqueeze_image(void* callback_wrapper, void __swift_bridge__$desqueeze_image$async(void* callback_wrapper, struct __private__ResultPtrAndPtr ret), struct RustStr image_path, struct RustStr output_path, void* image_format, void* squeeze_factor);


